services:
  postgres:
    image: postgres:15
    container_name: prac-2-psql-container
    environment:
      POSTGRES_USER: wasp
      POSTGRES_PASSWORD: supa-secure
      POSTGRES_DB: prac-2-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: prac-2-redis-container
    ports:
      - "6379:6379"

volumes:
  pgdata:
